/* Shared data layer + DOM/format helpers for the la-events dashboard.
 *
 * One fetch of ./data.json (generated by scripts/build_dashboard.py) feeds every view.
 * Scoring/rating/enrichment are precomputed server-side — this is a pure viewer.
 *
 * IMPORTANT: the helpers here read the REAL catalog schema as committed in data.json:
 *   start (HH:MM:SS), price (free-text string), links[{source,url}], detail, afterhours,
 *   ra_pick, lineup[], enrichment{curator_note,type,subgenres,artist_notes,image,...}.
 * (An earlier dashboard read tickets/url/start_time/description/price_min — fields that
 *  don't exist in the feed, so links/times/prices silently never rendered. Fixed here.)
 */

/* ── Shared app state + a tiny pub/sub so views can talk ─────────────────── */
export const App = {
  feed: null,
  saved: loadSaved(),                 // Set of event keys the user starred for a plan
  explore: defaultExploreState(),
  _listeners: {},
};

export function defaultExploreState() {
  return { q: "", cats: new Set(), hood: "", from: "", to: "", minRating: 0,
           free: false, hidePast: true, sortBy: "date" };
}

export function on(evt, fn) { (App._listeners[evt] ||= []).push(fn); }
export function emit(evt, data) { (App._listeners[evt] || []).forEach((fn) => fn(data)); }

export async function loadFeed() {
  const res = await fetch("./data.json", { cache: "no-store" });
  if (!res.ok) throw new Error(`data.json ${res.status}`);
  App.feed = await res.json();
  return App.feed;
}

/* ── Saved-events set (localStorage) — the seed for "plan around these" ───── */
function loadSaved() {
  try { return new Set(JSON.parse(localStorage.getItem("la-saved") || "[]")); }
  catch { return new Set(); }
}
export function isSaved(ev) { return App.saved.has(eventKey(ev)); }
export function toggleSaved(ev) {
  const k = eventKey(ev);
  App.saved.has(k) ? App.saved.delete(k) : App.saved.add(k);
  localStorage.setItem("la-saved", JSON.stringify([...App.saved]));
  emit("saved:change", App.saved);
  return App.saved.has(k);
}
export function savedEvents() {
  if (!App.feed) return [];
  return App.feed.events.filter((e) => App.saved.has(eventKey(e)));
}

/* Stable client-side key (mirrors lib/enrich.event_key intent: title|date|venue). */
export function eventKey(ev) {
  const t = (ev.title || "").toLowerCase().trim();
  const v = (ev.venue || "").toLowerCase().trim();
  const d = (ev.iso_date || ev.date || "").slice(0, 10);
  return `${t}|${d}|${v}`;
}

/* ── Tiny DOM helper ─────────────────────────────────────────────────────── */
export const $ = (sel, root = document) => root.querySelector(sel);
export const $$ = (sel, root = document) => [...root.querySelectorAll(sel)];
export const el = (tag, props = {}, ...kids) => {
  const { dataset, ...rest } = props;
  const node = Object.assign(document.createElement(tag), rest);
  if (dataset) Object.assign(node.dataset, dataset);
  for (const k of kids) if (k != null && k !== false) node.append(k);
  return node;
};

/* ── Formatting (LA conventions: "Day M/D", no leading zeros) ────────────── */
const DOW = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export const CAT_LABELS = {
  electronic: "Electronic", party: "Party", live_music: "Live Music", music: "Live Music",
  comedy: "Comedy", film: "Film", theater: "Theater", beer_food: "Beer & Food",
  art: "Art", pop: "Pop", multi: "Mixed", general: "Other",
};
export const catLabel = (c) => CAT_LABELS[c] || (c || "Other");

export function fmtDateChip(iso) {
  const [y, m, d] = iso.split("-").map(Number);
  return { dow: DOW[new Date(y, m - 1, d).getDay()], md: `${m}/${d}` };
}

export function fmtTime(start) {
  if (!start) return "";
  const m = /^(\d{1,2}):(\d{2})/.exec(start);
  if (!m) return "";
  let h = +m[1]; const mn = m[2];
  const ap = h < 12 ? "AM" : "PM";
  let h12 = h % 12; if (h12 === 0) h12 = 12;
  return mn === "00" ? `${h12} ${ap}` : `${h12}:${mn} ${ap}`;
}

/* Ticket/info links: dedupe by URL, label by domain (or source key). */
const DOMAIN_LABELS = [
  [/ra\.co/, "RA"], [/dice\.fm/, "DICE"], [/eventbrite\./, "Eventbrite"],
  [/posh\.vip/, "Posh"], [/universe\.com/, "Universe"], [/ticketmaster\./, "Ticketmaster"],
  [/ticketweb\./, "TicketWeb"], [/seetickets/, "See Tickets"], [/goldenvoice/, "Goldenvoice"],
  [/vidiots/, "Vidiots"], [/squarespace|\.com\/.*format=json/, "Tickets"],
];
const SOURCE_LABELS = {
  tm: "Tickets", ra: "RA", dice: "DICE", eventbrite: "Eventbrite", posh: "Posh",
  filmbot: "Showtimes", goldenvoice: "Goldenvoice", squarespace: "Tickets",
  ics: "Calendar", jsonld: "Tickets", "19hz": "19hz",
};
export function dedupeLinks(links) {
  const seen = new Set(); const out = [];
  for (const l of links || []) {
    if (!l || !l.url || seen.has(l.url)) continue;
    seen.add(l.url); out.push(l);
  }
  return out;
}
export function linkLabel(l) {
  for (const [re, label] of DOMAIN_LABELS) if (re.test(l.url || "")) return label;
  return SOURCE_LABELS[l.source] || (l.source ? l.source.toUpperCase() : "Tickets");
}

/* price is a free-text string in the feed ("$23", "free w/rsvp b4 1 / $23", null). */
export function priceLabel(ev) { return ev.price ? String(ev.price).trim() : ""; }
export function isFreeish(ev) { return /\bfree\b|no cover/i.test(ev.price || ""); }

export function isLovedVenue(ev) {
  const loved = (App.feed?.taste?.venues_loved || []).map((v) => v.toLowerCase());
  return loved.includes((ev.venue || "").toLowerCase());
}

export function trackedInLineup(ev) {
  const tracked = (App.feed?.taste?.artists_tracked || []).map((a) => a.toLowerCase());
  const hay = [...(ev.lineup || []), ev.title || ""].join(" ").toLowerCase();
  return (App.feed?.taste?.artists_tracked || []).filter((a) => hay.includes(a.toLowerCase()));
}

export function starsNode(n) {
  const wrap = el("span", { className: "stars" });
  for (let i = 1; i <= 5; i++) wrap.append(el("span", { textContent: "★", className: i <= n ? "" : "empty" }));
  return wrap;
}
