#!/usr/bin/env python3
"""Digest freshness gate — skip needless narrative regeneration, but always state freshness (Q2).

A profile's narrative digest (`digests/<hash>/latest.md`) is LLM-written prose, regenerated by the
daily routine. Re-writing it every night even when that profile's picks didn't move is the clearest
needless token spend. This gate makes the routine SKIP the LLM when nothing changed — and, either
way, keeps an honest one-line freshness stamp in the digest so it's always clear when it was last
regenerated, when it was last checked, and whether anything changed.

A digest's *signature* is a hash of its feed's top-N picks (event identity + final rank + verdict
tier). It moves when the catalog moves OR the profile's taste re-ranks — exactly when the prose
would actually say something new.

  decide --feed F --md D   -> prints REGENERATE (signature moved / no prior digest) or SKIP.
                              On SKIP: rewrites the digest's freshness line to "checked <today> ·
                              no new picks since <when>" and bumps the sidecar's checked_at.
  stamp  --feed F --md D    -> after the routine regenerates the prose: records the new signature +
                              generated_at and writes the "Regenerated <today>" freshness line.

Sidecar: `<md>.meta.json` = {signature, generated_at, checked_at, top_n}. Stdlib + lib only, so the
CI jobs need no extra deps.
"""

import argparse
import hashlib
import json
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # scripts/ on path
from lib.dedupe import normalize  # noqa: E402
from lib.pipeline import today_la  # noqa: E402

DEFAULT_TOP_N = 25
FRESH_PREFIX = "*Digest "          # the freshness line starts with this (so we can find + replace it)


def _events(feed: dict) -> list:
    return feed.get("events") if isinstance(feed, dict) else (feed or [])


def feed_signature(feed: dict, top_n: int = DEFAULT_TOP_N) -> str:
    """Hash the profile's top-N upcoming picks: identity + final rank + verdict tier. Order-stable."""
    today = today_la().isoformat()
    upcoming = [e for e in _events(feed)
                if not e.get("is_past") and (e.get("iso_date") or "") >= today]
    # Best-first by the editor-adjusted final rank when present (1 = best), else by taste rating.
    upcoming.sort(key=lambda e: (e.get("final_rank") if e.get("final_rank") is not None else 10**6,
                                 -(e.get("rating") or 0)))
    rows = []
    for e in upcoming[:top_n]:
        ident = f"{normalize(e.get('title',''))}|{(e.get('iso_date') or '')[:10]}|{normalize(e.get('venue',''))}"
        tier = ((e.get("verdict") or {}).get("tier")) or ""
        rows.append(f"{ident}|{e.get('final_rank')}|{tier}")
    # Fold in the profile's digest FORMAT prefs so a pure format change (no pick movement) still
    # forces exactly ONE regeneration — otherwise the gate would SKIP and the new format never lands.
    prefs = (feed.get("profile") or {}).get("digest_prefs") if isinstance(feed, dict) else None
    if prefs:
        rows.append("prefs:" + json.dumps(prefs, sort_keys=True, separators=(",", ":")))
    return hashlib.sha256("\n".join(rows).encode("utf-8")).hexdigest()[:16]


def meta_path(md_path: Path) -> Path:
    return md_path.with_suffix(md_path.suffix + ".meta.json")


def load_meta(md_path: Path) -> dict:
    try:
        return json.loads(meta_path(md_path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def save_meta(md_path: Path, meta: dict) -> None:
    meta_path(md_path).write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")


def _daylabel(iso: str) -> str:
    try:
        d = date.fromisoformat(iso[:10])
        return f"{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][d.weekday()]} {d.month}/{d.day}"
    except (ValueError, TypeError):
        return iso[:10] if iso else "—"


def freshness_text(meta: dict, today: date, regenerated: bool) -> str:
    """The one honest line (Q2): when it was last regenerated, when last checked, what changed."""
    gen = _daylabel(meta.get("generated_at", ""))
    chk = _daylabel(today.isoformat())
    if regenerated:
        return f"{FRESH_PREFIX}regenerated {chk} — picks updated.*"
    return f"{FRESH_PREFIX}regenerated {gen} · checked {chk} · no new picks since.*"


def upsert_freshness_line(md_text: str, line: str) -> str:
    """Idempotently set the freshness line — replace an existing one, else insert it right after the
    first heading (or at the very top if there's no heading)."""
    out_lines, replaced = [], False
    for ln in md_text.splitlines():
        if ln.startswith(FRESH_PREFIX):
            out_lines.append(line)
            replaced = True
        else:
            out_lines.append(ln)
    if replaced:
        return "\n".join(out_lines) + ("\n" if md_text.endswith("\n") else "")
    # Insert after the first H1/H2 heading, else at the top.
    idx = 0
    for i, ln in enumerate(out_lines):
        if ln.startswith("#"):
            idx = i + 1
            break
    out_lines.insert(idx, line)
    if idx + 1 >= len(out_lines) or out_lines[idx + 1].strip():
        out_lines.insert(idx + 1, "")          # keep a blank line after it
    return "\n".join(out_lines) + "\n"


def _write_line(md_path: Path, meta: dict, today: date, regenerated: bool) -> None:
    line = freshness_text(meta, today, regenerated)
    if md_path.exists():
        md_path.write_text(upsert_freshness_line(md_path.read_text(encoding="utf-8"), line), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("mode", choices=["decide", "stamp"])
    ap.add_argument("--feed", required=True, help="the profile feed JSON (dashboard/data[.hash].json)")
    ap.add_argument("--md", required=True, help="the narrative digest markdown to gate/stamp")
    ap.add_argument("--top-n", type=int, default=DEFAULT_TOP_N)
    args = ap.parse_args()

    md_path = Path(args.md)
    try:
        feed = json.loads(Path(args.feed).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        print(f"REGENERATE  (feed unreadable: {e})")     # fail open — better to regenerate than skip silently
        return 0
    sig = feed_signature(feed, args.top_n)
    meta = load_meta(md_path)
    today = today_la()

    if args.mode == "stamp":
        meta.update({"signature": sig, "generated_at": today.isoformat(),
                     "checked_at": today.isoformat(), "top_n": args.top_n})
        save_meta(md_path, meta)
        _write_line(md_path, meta, today, regenerated=True)
        print(f"STAMPED  sig={sig}")
        return 0

    # decide
    fresh = bool(meta.get("signature")) and meta["signature"] == sig and md_path.exists()
    meta["checked_at"] = today.isoformat()
    if fresh:
        save_meta(md_path, meta)
        _write_line(md_path, meta, today, regenerated=False)
        print(f"SKIP  (signature unchanged: {sig})")
    else:
        save_meta(md_path, meta)        # record the check; generated_at updates when stamp runs
        why = "no prior digest" if not meta.get("signature") else "picks changed"
        print(f"REGENERATE  ({why}; sig {meta.get('signature')} -> {sig})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
